import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
import { mkdir, copyFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire(process.env.PROOF_PLAYWRIGHT_PACKAGE || path.join(root,'package.json'));
const {chromium}=require('playwright');
const out=path.join(root,'docs','images');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:960},recordVideo:{dir:path.join(root,'proof-results'),size:{width:1440,height:960}}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
function step(name){const r=spawnSync(process.env.PROOF_PYTHON||path.join(root,'.venv',process.platform==='win32'?'Scripts/python.exe':'bin/python'),[path.join(root,'proof','demo_step.py'),name],{cwd:path.join(root,'backend'),encoding:'utf8',env:process.env});if(r.status!==0)throw Error(r.stderr);console.log(name,r.stdout.trim())}
await page.goto('http://127.0.0.1:8090/proof');
await page.locator('input[name=username]').fill(process.env.FIRST_SUPERUSER);
await page.locator('input[name=password]').fill(process.env.FIRST_SUPERUSER_PASSWORD);
await page.getByRole('button',{name:'Sign in',exact:true}).click();
await page.getByRole('button',{name:'Refresh evidence'}).waitFor();
step('happy');await page.getByRole('button',{name:'Refresh evidence'}).click();await page.locator('#deliveries .delivered').waitFor();await page.waitForTimeout(1600);
step('duplicate');await page.getByRole('button',{name:'Refresh evidence'}).click();await page.waitForTimeout(1400);if(await page.locator('#deliveries tr').count()!==1)throw Error('Duplicate input produced extra delivery');
step('lost');await page.getByRole('button',{name:'Refresh evidence'}).click();await page.locator('#deliveries .retry').waitFor();await page.screenshot({path:path.join(out,'lost-response.png'),fullPage:true});await page.waitForTimeout(2500);
step('recover');await page.getByRole('button',{name:'Refresh evidence'}).click();await page.waitForTimeout(1500);
step('reject');await page.getByRole('button',{name:'Refresh evidence'}).click();await page.locator('#deliveries .dead').waitFor();await page.waitForTimeout(1800);
page.once('dialog',async d=>d.accept('Inspected partner rejection and corrected test configuration'));
await page.getByRole('button',{name:'Replay',exact:true}).click();await page.waitForTimeout(800);step('recover');await page.getByRole('button',{name:'Refresh evidence'}).click();await page.waitForTimeout(1000);
if(await page.locator('#deliveries .delivered').count()!==3)throw Error('Expected three delivered versions');
await page.screenshot({path:path.join(out,'delivery-console.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile page overflows viewport');await page.screenshot({path:path.join(out,'mobile-console.png'),fullPage:true});
await page.setViewportSize({width:1440,height:960});await page.getByRole('button',{name:'Sign out'}).click();await page.getByRole('button',{name:'Sign in',exact:true}).waitFor();
await context.close();await copyFile(await page.video().path(),path.join(out,'recovery-demo.webm'));await browser.close();
if(errors.length)throw Error(errors.join('\n'));console.log('Browser PASS: login, duplicate, timeout, recovery, audited replay, mobile, logout; no page errors');
